import type { CookbookPage } from '@/types/cookbook';

export const SAMPLE_COOKBOOK_ID = 'sample-cookbook';

export const SAMPLE_COOKBOOK_PAGES: CookbookPage[] = [
  {
    id: 'sample-lemon-herb-chicken',
    cookbookId: SAMPLE_COOKBOOK_ID,
    recipeId: 'sample-recipe-lemon-herb-chicken',
    title: 'Lemon Herb Roast Chicken',
    section: 'dinner',
    pageNumber: 1,
    sortOrder: 1,
    isSample: true,
    recipe: {
      id: 'sample-recipe-lemon-herb-chicken',
      title: 'Lemon Herb Roast Chicken',
      description: 'A golden one-pan supper with soft potatoes, bright lemon, and garden herbs.',
      servings: 4,
      prepTime: 15,
      cookTime: 55,
      ingredients: [
        { quantity: '1', unit: 'whole', name: 'chicken, patted dry' },
        { quantity: '1 1/2', unit: 'lb', name: 'baby potatoes, halved' },
        { quantity: '2', unit: 'tbsp', name: 'olive oil' },
        { quantity: '1', unit: 'lemon', name: 'thinly sliced' },
        { quantity: '4', unit: 'cloves', name: 'garlic, smashed' },
        { quantity: '2', unit: 'tsp', name: 'chopped rosemary and thyme' },
      ],
      steps: [
        'Heat oven to 425 F. Toss potatoes with oil, garlic, herbs, salt, and pepper.',
        'Rub chicken with oil, lemon zest, herbs, and a generous pinch of salt.',
        'Nestle chicken over potatoes and roast until deeply golden and cooked through.',
        'Rest 10 minutes, spoon pan juices over the top, and serve with lemon slices.',
      ],
      sourceType: 'text',
      tags: ['sample', 'one-pan'],
      category: 'dinner',
      confidence: 1,
    },
  },
  {
    id: 'sample-blueberry-oat-muffins',
    cookbookId: SAMPLE_COOKBOOK_ID,
    recipeId: 'sample-recipe-blueberry-oat-muffins',
    title: 'Blueberry Oat Morning Muffins',
    section: 'breakfast',
    pageNumber: 2,
    sortOrder: 2,
    isSample: true,
    recipe: {
      id: 'sample-recipe-blueberry-oat-muffins',
      title: 'Blueberry Oat Morning Muffins',
      description: 'Tender muffins with jammy berries, oats, and a cinnamon sugar crown.',
      servings: 12,
      prepTime: 12,
      cookTime: 18,
      ingredients: [
        { quantity: '1 1/2', unit: 'cups', name: 'all-purpose flour' },
        { quantity: '1', unit: 'cup', name: 'rolled oats' },
        { quantity: '2', unit: 'tsp', name: 'baking powder' },
        { quantity: '1/2', unit: 'cup', name: 'brown sugar' },
        { quantity: '1', unit: 'cup', name: 'milk' },
        { quantity: '1 1/2', unit: 'cups', name: 'blueberries' },
      ],
      steps: [
        'Whisk dry ingredients in a large bowl and wet ingredients in a second bowl.',
        'Fold wet into dry until just combined, then gently fold in blueberries.',
        'Divide into a lined muffin tin and sprinkle with cinnamon sugar.',
        'Bake at 375 F until domed and golden, 16 to 18 minutes.',
      ],
      sourceType: 'text',
      tags: ['sample', 'breakfast'],
      category: 'breakfast',
      confidence: 1,
    },
  },
  {
    id: 'sample-tomato-bean-soup',
    cookbookId: SAMPLE_COOKBOOK_ID,
    recipeId: 'sample-recipe-tomato-bean-soup',
    title: 'Tomato White Bean Soup',
    section: 'healthy',
    pageNumber: 3,
    sortOrder: 3,
    isSample: true,
    recipe: {
      id: 'sample-recipe-tomato-bean-soup',
      title: 'Tomato White Bean Soup',
      description: 'A cozy pantry soup finished with basil oil and a little parmesan.',
      servings: 4,
      prepTime: 10,
      cookTime: 25,
      ingredients: [
        { quantity: '1', unit: 'tbsp', name: 'olive oil' },
        { quantity: '1', unit: 'small', name: 'onion, diced' },
        { quantity: '3', unit: 'cloves', name: 'garlic, minced' },
        { quantity: '28', unit: 'oz', name: 'crushed tomatoes' },
        { quantity: '2', unit: 'cans', name: 'white beans, drained' },
        { quantity: '2', unit: 'cups', name: 'vegetable broth' },
      ],
      steps: [
        'Soften onion in olive oil, then stir in garlic until fragrant.',
        'Add tomatoes, beans, broth, salt, and pepper. Simmer 20 minutes.',
        'Mash a few beans against the pot to thicken the soup.',
        'Finish with basil, parmesan, and toasted bread.',
      ],
      sourceType: 'text',
      tags: ['sample', 'healthy'],
      category: 'healthy',
      confidence: 1,
    },
  },
];
