import { COOKBOOK_GEOMETRY } from '../../../constants/cookbookGeometry.ts';
import { RECIPE_PAGE_GENERATION_STAGE_VERSION } from './captureStages.ts';

export interface CookbookPageImageDimensions {
  width: number;
  height: number;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

/**
 * A ready version is reusable only when it records the complete current page
 * contract. This prevents publication retries from reviving pages generated by
 * an older deployment with a different canvas proportion.
 */
export function isCanonicalCookbookPageGenerationPayload(value: unknown): boolean {
  if (!isRecord(value) || !isRecord(value.output)) return false;
  return value.kind === 'complete-recipe-page'
    && value.generationContractVersion === RECIPE_PAGE_GENERATION_STAGE_VERSION
    && value.geometryId === COOKBOOK_GEOMETRY.id
    && value.geometryRevision === COOKBOOK_GEOMETRY.revision
    && value.output.aspectRatio === COOKBOOK_GEOMETRY.generation.aspectRatio;
}

function readPngDimensions(bytes: Uint8Array): CookbookPageImageDimensions | null {
  if (bytes.length < 24) return null;
  const signature = [137, 80, 78, 71, 13, 10, 26, 10];
  if (!signature.every((byte, index) => bytes[index] === byte)) return null;
  if (String.fromCharCode(...bytes.slice(12, 16)) !== 'IHDR') return null;

  const view = new DataView(bytes.buffer, bytes.byteOffset, bytes.byteLength);
  const width = view.getUint32(16, false);
  const height = view.getUint32(20, false);
  return width > 0 && height > 0 ? { width, height } : null;
}

/**
 * Validate the provider's actual PNG rather than trusting request metadata.
 * A small tolerance allows integer-sized 4:5 outputs such as 1122 x 1402.
 */
export function assertCanonicalCookbookPageImage(
  bytes: Uint8Array,
): CookbookPageImageDimensions {
  const dimensions = readPngDimensions(bytes);
  if (!dimensions) throw new Error('Generated cookbook page was not a readable PNG');

  const actualRatio = dimensions.width / dimensions.height;
  if (Math.abs(actualRatio - COOKBOOK_GEOMETRY.page.aspectRatio) > 0.005) {
    throw new Error(
      `Generated cookbook page did not match canonical ${COOKBOOK_GEOMETRY.generation.aspectRatio} geometry`,
    );
  }
  return dimensions;
}
