/**
 * ArtLayer — the Skia Canvas that renders the generated art asset and
 * decorative elements (borders, accent rules, ornaments) for a cookbook page.
 *
 * This layer contains NO text. It is purely visual. The TextLayer renders
 * the recipe text on top of this layer as native React Native Views.
 *
 * The art asset is a no-text PNG generated by the generate-page-art Edge
 * Function. It's loaded via Skia's useImage hook from a Supabase Storage URL.
 */

import React, { memo, useMemo } from 'react';
import { StyleSheet } from 'react-native';
import { Canvas, Image, Rect, RoundedRect, useImage } from '@shopify/react-native-skia';
import type { TypesetterStyleConfig } from '@/constants/typesetterStyles';
import type { TypesetterLayoutConfig } from '@/constants/typesetterLayouts';

export interface ArtLayerProps {
  /** Page width in pixels. */
  width: number;
  /** Page height in pixels. */
  height: number;
  /** The art asset URL (Supabase Storage). Null/undefined while art is generating. */
  artUrl?: string | null;
  /** The typesetter style config for this page's cookbook style. */
  styleConfig: TypesetterStyleConfig;
  /** The typesetter layout config for this page's recipe template. */
  layoutConfig: TypesetterLayoutConfig;
}

/**
 * Compute the art rectangle (position and size of the art asset on the page).
 * The art occupies the top portion of the page, centered or full-width
 * depending on the layout config.
 */
function computeArtRect(
  width: number,
  height: number,
  styleConfig: TypesetterStyleConfig,
  layoutConfig: TypesetterLayoutConfig,
): { x: number; y: number; w: number; h: number } {
  const margin = width * styleConfig.marginRatio;
  const contentWidth = width - margin * 2;
  const artHeight = height * styleConfig.artHeightRatio;
  const artWidth = contentWidth * layoutConfig.artWidthRatio;

  const x = layoutConfig.artCentered
    ? margin + (contentWidth - artWidth) / 2
    : margin;

  return { x, y: margin * 0.6, w: artWidth, h: artHeight };
}

export const ArtLayer = memo(function ArtLayer({
  width,
  height,
  artUrl,
  styleConfig,
  layoutConfig,
}: ArtLayerProps) {
  const artImage = useImage(artUrl ?? undefined);
  const artRect = useMemo(
    () => computeArtRect(width, height, styleConfig, layoutConfig),
    [width, height, styleConfig, layoutConfig],
  );

  const margin = width * styleConfig.marginRatio;
  const borderInset = width * styleConfig.borderInsetRatio;
  const titleRuleY = artRect.y + artRect.h + height * layoutConfig.artTextGapRatio;

  return (
    <Canvas style={[styles.canvas, { width, height }]}>
      {/* Page background */}
      <Rect x={0} y={0} width={width} height={height} color={styleConfig.paperColor} />

      {/* Art asset */}
      {artImage ? (
        <Image
          image={artImage}
          fit="contain"
          x={artRect.x}
          y={artRect.y}
          width={artRect.w}
          height={artRect.h}
        />
      ) : null}

      {/* Accent rule between art and text */}
      <Rect
        x={margin}
        y={titleRuleY}
        width={width - margin * 2}
        height={1}
        color={styleConfig.accentColor}
        opacity={styleConfig.accentRuleOpacity}
      />

      {/* Decorative border (vintage/rustic/charcoal/umber styles) */}
      {styleConfig.showBorder ? (
        <RoundedRect
          x={borderInset}
          y={borderInset}
          width={width - borderInset * 2}
          height={height - borderInset * 2}
          r={0}
          style="stroke"
          strokeWidth={1}
          color={styleConfig.inkColor}
          opacity={0.12}
        />
      ) : null}

      {/* Small ornament dot near art (botanical/editorial styles) */}
      {styleConfig.showArtOrnament && artImage ? (
        <Rect
          x={width / 2 - 2}
          y={titleRuleY + 6}
          width={4}
          height={4}
          color={styleConfig.accentColor}
          opacity={styleConfig.accentRuleOpacity * 0.8}
        />
      ) : null}
    </Canvas>
  );
});

const styles = StyleSheet.create({
  canvas: {
    position: 'absolute',
    top: 0,
    left: 0,
  },
});
